server:
  port: 8080

spring:
  application:
    name: spring-idempotency-aop
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.data.redis.RedisReactiveHealthContributorAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 3000ms

management:
  endpoints:
    web:
      exposure:
        include: health, info
